if (WIN32)
	set (DEFAULT_PATH_RAGEL_EXE        "c:/Develop/FlexBison/ragel.exe")
	set (DEFAULT_PATH_LUA_INC_DIR      "c:/Develop/Lua/inc")
	set (DEFAULT_PATH_LUA_LIB_DIR      "c:/Develop/Lua/lib/x86/$(Configuation)")
	set (DEFAULT_PATH_LLVM_CMAKE_DIR   "c:/Develop/LLVM/llvm-3.2.msvc10_x86/share/llvm/cmake")
	set (DEFAULT_PATH_LLVM_INC_DIR     "c:/Develop/LLVM/llvm-3.2.src/include")
	set (DEFAULT_PATH_LLVM_INC_DIR_2   "c:/Develop/LLVM/llvm-3.2.msvc10_x86/include")
	set (DEFAULT_PATH_LLVM_LIB_DIR     "c:/Develop/LLVM/llvm-3.2.msvc10_x86/lib/$(Configuation)")
	set (DEFAULT_PATH_QT_CMAKE_DIR     "c:/Develop/QT/qt-5.0.2/5.0.2/msvc2010/lib/cmake")
else ()
	set (DEFAULT_PATH_RAGEL_EXE        "ragel")
	set (DEFAULT_PATH_LUA_INC_DIR      "/home/vladimir/Develop/Lua/lua-5.2.1/include")
	set (DEFAULT_PATH_LUA_LIB_DIR      "/home/vladimir/Develop/Lua/lua-5.2.1/lib/amd64")
	set (DEFAULT_PATH_LLVM_CMAKE_DIR   "/home/vladimir/Develop/Llvm/llvm-3.2.make_amd64/share/llvm/cmake")
	set (DEFAULT_PATH_LLVM_INC_DIR     "/home/vladimir/Develop/Llvm/llvm-3.2.src/include")
	set (DEFAULT_PATH_LLVM_INC_DIR_2   "/home/vladimir/Develop/Llvm/llvm-3.2.make_amd64/include")
	set (DEFAULT_PATH_LLVM_LIB_DIR     "/home/vladimir/Develop/Llvm/llvm-3.2.make_amd64/lib")
	set (DEFAULT_PATH_QT_CMAKE_DIR     "/home/vladimir/Develop/QT/5.0.2/gcc_64/lib/cmake")
endif ()
