name: Default CI Workflow

on:
-   push
-   pull_request

jobs:
    windowsBuild:
        name: Windows Build (Visual Studio 15 2017)
        runs-on: windows-2016
        strategy:
            fail-fast: false
            matrix:
                TOOLCHAIN:
                -   msvc10
                -   msvc15

                CONFIGURATION:
                -   Debug
                -   Release

                TARGET_CPU:
                -   x86
                -   amd64

        steps:
        -   name: Checkout repo
            uses: actions/checkout@v2

        -   name: Build and test
            shell: cmd
            run: |
                call ci\github-actions\set-env.bat ${{matrix.TOOLCHAIN}} ${{matrix.TARGET_CPU}} ${{matrix.CONFIGURATION}}

                set
                dir C:\
                dir "C:\Program Files\OpenSSL"
                dir "C:\Program Files"
                dir "C:\Program Files (x86)"

                mkdir build
                cd build
                cmake .. %CMAKE_CONFIGURE_FLAGS% || exit
                cmake --build . %CMAKE_BUILD_FLAGS% || exit
                ctest -C %CONFIGURATION% || exit

    linuxBuild:
        name: Linux Build
        runs-on: ubuntu-18.04
        strategy:
            fail-fast: false
            matrix:
                CONFIGURATION:
                -   Debug
                -   Release

                TARGET_CPU:
                -   x86
                -   amd64

        steps:
        -   name: Install
            shell: bash
            run: source /ci/github-actions/install-linux.sh

        -   name: Checkout repo
            uses: actions/checkout@v2

        -   name: Build and test
            shell: bash
            run: |
                mkdir build
                cd build
                cmake .. -DTARGET_CPU=${{matrix.TARGET_CPU}} -DCMAKE_BUILD_TYPE=${{matrix.CONFIGURATION}}
                make
                ctest --output-on-failure

    macOsBuild:
        name: macOS Build
        runs-on: macos-10.15
        strategy:
            fail-fast: false
            matrix:
                CONFIGURATION:
                -   Debug
                -   Release

        steps:
        -   name: Checkout repo
            uses: actions/checkout@v2

        -   name: Install
            shell: bash
            run: source /ci/github-actions/install-osx.sh

        -   name: Build and test
            shell: bash
            run: |
                mkdir build
                cd build
                cmake .. -DCMAKE_BUILD_TYPE=${{matrix.CONFIGURATION}}
                make
                ctest --output-on-failure
