name: GitHub CI

on:
-   push
-   pull_request

jobs:
    windowsBuild:
        name: Windows Build
        runs-on: windows-2016
        strategy:
            fail-fast: false
            matrix:
                CONFIGURATION:
                -   Debug
                # -   Release

                TARGET_CPU:
                # -   x86
                -   amd64

        steps:
        -   name: Checkout repo
            uses: actions/checkout@v2

        -   name: Install
            shell: cmd
            run: |
                call ci\github-actions\set-env.bat msvc10 ${{matrix.TARGET_CPU}}
                call ci\github-actions\install-windows.bat

        -   name: Build and test
            shell: cmd
            run: |
                set CONFIGURATION=${{matrix.CONFIGURATION}}
                call ci\github-actions\set-env.bat msvc15 ${{matrix.TARGET_CPU}}

                dir "C:\Program Files (x86)\Microsoft Visual Studio 10.0"

                mkdir build
                cd build
                cmake .. %CMAKE_CONFIGURE_FLAGS% || exit
                cmake --build . %CMAKE_BUILD_FLAGS% || exit
                ctest --output-on-failure -C %CONFIGURATION% || exit

#    linuxBuild:
#        name: Linux Build
#        runs-on: ubuntu-18.04
#        strategy:
#            fail-fast: false
#            matrix:
#                CONFIGURATION:
#                -   Debug
#                -   Release
#
#                TARGET_CPU:
#                -   x86
#                -   amd64
#
#        steps:
#        -   name: Checkout repo
#            uses: actions/checkout@v2
#
#        -   name: Install
#            shell: bash
#            run: |
#                export TARGET_CPU=${{matrix.TARGET_CPU}}
#                source ./ci/github-actions/install-linux.sh
#
#        -   name: Build and test
#            shell: bash
#            run: |
#                mkdir build
#                cd build
#                cmake .. -DTARGET_CPU=${{matrix.TARGET_CPU}} -DCMAKE_BUILD_TYPE=${{matrix.CONFIGURATION}}
#                make
#                ctest --output-on-failure
#
#    macOsBuild:
#        name: macOS Build
#        runs-on: macos-10.15
#        strategy:
#            fail-fast: false
#            matrix:
#                CONFIGURATION:
#                -   Debug
#                -   Release
#
#        steps:
#        -   name: Checkout repo
#            uses: actions/checkout@v2
#
#        -   name: Install
#            shell: bash
#            run: |
#                pwd
#                source ./ci/github-actions/install-osx.sh
#
#        -   name: Build and test
#            shell: bash
#            run: |
#                mkdir build
#                cd build
#                cmake .. -DCMAKE_BUILD_TYPE=${{matrix.CONFIGURATION}}
#                make
#                ctest --output-on-failure
