name: GitHub CI

on:
-   push
-   pull_request

jobs:
    windowsBuild:
        name: Windows Build
        runs-on: windows-2019

        strategy:
            fail-fast: false
            matrix:
                CONFIGURATION:
                -   Debug
                -   Release

                TARGET_CPU:
                -   x86
                -   amd64

        steps:
        -   name: Checkout repo
            uses: actions/checkout@v3

        -   name: Install
            shell: cmd
            run: |
                call ci\github-actions\set-env.bat ${{matrix.TARGET_CPU}}
                call ci\github-actions\install-windows.bat
                git clone --branch re2s-no-abseil --depth 1 https://github.com/vovkos/re2s

        -   name: Build and test
            shell: cmd
            run: |
                set CONFIGURATION=${{matrix.CONFIGURATION}}
                set THIS_DIR=%CD%
                set THIS_DIR_CMAKE=%THIS_DIR:\=/%

                call ci\github-actions\set-env.bat msvc16 ${{matrix.TARGET_CPU}}

                mkdir re2s\.build
                cd re2s\.build
                cmake .. -DCMAKE_INSTALL_PREFIX=%THIS_DIR_CMAKE%/re2s/install || exit
                cmake --build . --target install %CMAKE_BUILD_FLAGS% || exit

                cd %THIS_DIR%
                echo set (RE2S_CMAKE_DIR %THIS_DIR_CMAKE%/re2s/install/lib/cmake/re2s) >> paths.cmake

                mkdir build
                cd build
                cmake .. %CMAKE_CONFIGURE_FLAGS% || exit
                cmake --build . %CMAKE_BUILD_FLAGS% || exit
                ctest --output-on-failure -C %CONFIGURATION% || exit

    linuxBuild:
        name: Linux Build
        runs-on: ubuntu-20.04
        strategy:
            fail-fast: false
            matrix:
                CONFIGURATION:
                -   Debug
                -   Release

                TARGET_CPU:
                -   x86
                -   amd64

                COMPILER:
                -   clang
                -   gcc

        steps:
        -   name: Checkout repo
            uses: actions/checkout@v3

        -   name: Install
            shell: bash
            run: |
                export TARGET_CPU=${{matrix.TARGET_CPU}}
                source ./ci/github-actions/install-linux.sh
                git clone --branch re2s-no-abseil --depth 1 https://github.com/vovkos/re2s

        -   name: Build and test
            shell: bash
            run: |
                export CC=$(which ${{matrix.COMPILER}})
                export CXX=$(which ${{matrix.COMPILER}}++)
                THIS_DIR=$(pwd)

                mkdir re2s/.build
                pushd re2s/.build
                cmake .. -DCMAKE_BUILD_TYPE=${{matrix.CONFIGURATION}} -DCMAKE_INSTALL_PREFIX=$THIS_DIR/re2s/install -DCMAKE_CXX_FLAGS=-fPIC
                make install
                popd

                echo set (RE2S_CMAKE_DIR $THIS_DIR/re2s/install/lib/cmake/re2s) >> paths.cmake

                mkdir build
                cd build
                cmake .. -DTARGET_CPU=${{matrix.TARGET_CPU}} -DCMAKE_BUILD_TYPE=${{matrix.CONFIGURATION}}
                make
                ctest --output-on-failure

    macOsBuild:
        name: macOS Build
        runs-on: macos-11
        strategy:
            fail-fast: false
            matrix:
                CONFIGURATION:
                -   Debug
                -   Release

        steps:
        -   name: Checkout repo
            uses: actions/checkout@v3

        -   name: Install
            shell: bash
            run: |
                pwd
                source ./ci/github-actions/install-osx.sh
                git clone --branch re2s-no-abseil --depth 1 https://github.com/vovkos/re2s

        -   name: Build and test
            shell: bash
            run: |
                THIS_DIR=$(pwd)

                mkdir re2s/.build
                pushd re2s/.build
                cmake .. -DCMAKE_BUILD_TYPE=${{matrix.CONFIGURATION}} -DCMAKE_INSTALL_PREFIX=$THIS_DIR/re2s/install -DCMAKE_CXX_FLAGS=-fPIC
                make install
                popd

                echo set (RE2S_CMAKE_DIR $THIS_DIR/re2s/install/lib/cmake/re2s) >> paths.cmake

                mkdir build
                cd build
                cmake .. -DCMAKE_BUILD_TYPE=${{matrix.CONFIGURATION}}
                make
                ctest --output-on-failure
