name: Default CI Workflow

on:
-   push
-   pull_request

jobs:
    ciWindows:
        name: Windows Build (Visual Studio 15 2017)
        runs-on: windows-2016
        steps:
        -   name: Checkout repo
            uses: actions/checkout@v2

        -   name: Build and test
            shell: pwsh
            run: |
                $ErrorActionPreference = "Stop"
                mkdir build
                cd build
                cmake .. -G "Visual Studio 15 2017 Win64"
                cmake --build . --config Debug
                ctest -C Debug
