name: Default CI Workflow

on:
-   push
-   pull_request

jobs:
    ciWindows:
        name: Windows Build (Visual Studio 15 2017)
        runs-on: windows-2016
        strategy:
            fail-fast: false
            matrix:
                CONFIGURATION:
                -   Debug
                -   Release

                TARGET_CPU:
                -   x86
                -   amd64

        steps:
        -   name: Checkout repo
            uses: actions/checkout@v2

        -   name: Build and test
            shell: cmd
            run: |
                set CMAKE_GENERATOR_SUFFIX=
                if "${{matrix.TARGET_CPU}}" == "amd64" (set CMAKE_GENERATOR_SUFFIX= Win64)

                mkdir build
                cd build
                cmake .. -G "Visual Studio 15 2017%CMAKE_GENERATOR_SUFFIX%" || exit
                cmake --build . --config ${{matrix.CONFIGURATION}} || exit
                ctest -C ${{matrix.CONFIGURATION}} || exit
